
persistence:
  enabled: true
  size: 2Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.pet-payment-billing-platform.svc.cluster.local
        isDefault: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.pet-payment-billing-platform.svc.cluster.local:3200
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.pet-payment-billing-platform.svc.cluster.local:3100


ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
