apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  LOG_CHANNEL: stderr
  LOG_LEVEL: info
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: identity
  DB_USERNAME: billing
  SESSION_DRIVER: array
  CACHE_STORE: database
  QUEUE_CONNECTION: sync
