apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: notification
      app.kubernetes.io/part-of: billing-platform
    includeSelectors: true
resources:
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - workloads.yaml
  - service.yaml
  - migrate-job.yaml
