apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: identity-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: identity-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: customer-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: customer-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: catalog-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: catalog-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: subscription-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: subscription-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: billing-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: billing-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: payment-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: payment-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: notification-api}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: notification-api}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
