apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  LOG_CHANNEL: stderr
  LOG_LEVEL: info
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: billing
  DB_USERNAME: billing
  SESSION_DRIVER: array
  CACHE_STORE: array
  QUEUE_CONNECTION: sync
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
