apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet-payment-billing-platform-gateway
  namespace: pet-payment-billing-platform
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.pet-payment-billing-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
