apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pet-payment-billing-platform

helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.173.0
    releaseName: otel-collector
    namespace: pet-payment-billing-platform
    valuesFile: values.yaml
