apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/part-of: billing-platform
    includeSelectors: true

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: rabbitmq-conf
    files:
      - rabbitmq.conf=../../../rabbitmq/rabbitmq.conf
      - definitions.json=../../../rabbitmq/definitions.json
