apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/component: broker
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: broker
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
