apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  labels:
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
