apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: identity, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: customer, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: catalog, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: subscription-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: subscription, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: billing, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: payment, app.kubernetes.io/component: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-api
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: notification, app.kubernetes.io/component: api}
