apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pet-payment-billing-platform

resources:
  - ../../base
  - ../../base/postgres
  - ../../base/rabbitmq
  - ../../base/customer
  - ../../base/catalog
  - ../../base/subscription
  - ../../base/billing
  - ../../base/gateway
  - ../../platform/ingress
